_talks/2018-01-17-working-with-others-using-git-and-github.md
To be merged after slides are finalised.
=> talks: Working with others using Git and GitHub.

_posts/2018-01-29-issues-with-first-timer-issues.md
Add a new post about first timer issues.
=> Issues with first timer issues

_posts/2018-02-14-translations-with-rails-and-jekyll.md
=> Translations With Rails And Jekyll

Rakefile, _posts/2007-02-27-making-dizzy-shine-with-ajax.html, talks/index.html
And change generated/fixed relevant files.
=> Rakefile: cleanup.

.travis.yml, Gemfile, Rakefile
- Update Ruby
- Cleanup Rakefile
- Cleanup Gemfile
=> Tweak Travis CI

_talks/2019-02-03-how-to-not-fail-at-using-open-source-software-in-your-organisation.md
To be merged after I've actually done it.
=> Homebrew 2.0.0 talk

_posts/2019-02-16-stop-mentoring-first-time-contributors.md
=> New post: Stop Mentoring First-Time Contributors.

_posts/2019-10-14-making-homebrew-financially-sustainable.md
=> Making Homebrew Financially Sustainable post

Rakefile
Tweak error codes to those I care about.
=> Rakefile: tweak http_status_ignore.

_includes/newsletter.html
This lets me autosend using RSS.
=> newsletter: use MailChimp.

projects.md
Looks like the descriptions of these two projects were reversed! 🔁
=> Fix two reversed project descriptions

_posts/2014-01-18-why-use-version-control.md, cv.md, gitinpractice.md, projects.md
=> Fix broken links

_posts/2020-12-15-my-engineering-values.md
=> Add "my engineering values" post.

_posts/2020-12-22-types-of-remote-jobs.md
As inspired by recent conversations in the Development & Technology Scotland's Slack.
=> Types of remote jobs

404.html, _layouts/article.html, _layouts/base.html, _layouts/page.html, _layouts/talk.html, _posts/2007-02-27-making-dizzy-shine-with-ajax.html, _posts/2010-09-19-windows-autologin-lock-screen.md, _posts/2012-01-04-deploying-qt-applications-with-deployqt4.md, _posts/2014-01-18-why-use-version-control.md, _posts/2014-11-23-working-from-home.md, _posts/2014-12-07-my-working-from-home-schedule.md, _posts/2016-03-30-long-distance-business-travel.md, _posts/2018-08-14-the-open-source-contributor-funnel-why-people-dont-contribute-to-your-open-source-project.md, _posts/2018-09-04-how-to-not-fail-at-using-open-source-software-in-your-organisation.md, _posts/2019-02-16-stop-mentoring-first-time-contributors.md, _posts/2019-07-22-how-being-a-dad-has-changed-how-i-work.md, _posts/2021-06-09-robot-pedantry-human-empathy.md, _posts/2021-07-21-how-i-get-things-done.md, _posts/2021-09-09-the-mentorship-diamond.md, _talks/2016-06-28-the-open-source-contributor-funnel.md, _talks/2017-05-10-why-people-dont-contribute-to-your-open-source-project.md, _talks/2018-08-02-how-to-not-fail-at-using-open-source-software-in-your-organisation.md, about.md, balancingdads.md, css/style.scss, cv.md, gitinpractice.md, index.html, projects.md, talks/index.html
Will fix rendering in RSS feed readers and Mailchimp.
=> Use absolute URLs

_posts/2007-02-27-making-dizzy-shine-with-ajax.html, _posts/2019-07-22-how-being-a-dad-has-changed-how-i-work.md, projects.md
=> More absolute_url fixes.

_posts/2021-11-08-stop-requiring-specific-technology-experience-for-senior-plus-engineers.md
=> Stop requiring specific technology experience for senior-plus engineers

.github/workflows/tests.yml, _talks/2021-11-09-homebrew-a-packagers-deep-dive.md
Use some new features and cache Bundler.
=> Cleanup GitHub Actions

_posts/2021-11-29-hidden-complexities-of-software-estimation.md, _talks/2021-10-27-open-source-economics.md
=> when-estimating-a-software-project-you-should-not: add new post.

_posts/2022-10-20-entitlement-in-open-source.md, _talks/2022-09-29-the-best-project.md
=> Add "The Best Project" talk.

_posts/2023-10-30-our-intentions-dont-matter.md
=> Add "Our Intentions Don't Matter" post

.github/workflows/tests.yml
=> Move to `main` default branch.

_talks/2023-11-22-open-source-boundaries-burnout-business.md, _talks/2024-02-04-homebrews-evolution.md
Add the two talks I'm doing at FOSDEM this year.
=> Add FOSDEM talks

css/style.scss, cv.md, projects.md, references.md
Use some CSS to make it nicer and adjust some links accordingly.
=> Improve print output

_posts/2025-04-07-two-years-building-workbrew-a-remote-first-enterprise-homebrew-startup.md, _posts/2025-04-15-how-and-why-i-interview-engineers-for-workbrew.md, _talks/2012-02-29-advanced-git.md, _talks/2012-06-05-how-to-make-os-x-users-not-hate-you.md, _talks/2012-06-05-html5.md
Add new blog post and add reference to existing post.
=> New post: How and why I interview engineers for Workbrew

Rakefile, _posts/2025-06-03-why-open-source-maintainers-thrive-in-the-llm-era.md
From a OSS maintainer perspective.
=> Add post on how I use LLMs/AI.
